### ISSUE TITLE
How to create user_roles collection

### ISSUE THREAD

**Issue by JKAngular** [AmitXShukla/ERP-Apps-CRM-Cloud-Angular_Firebase#1]
Hi
I saw your video . how to create user_roles collection and you share collection structure for this 
user_roles  . your video shows already created shows 

so i need how to create user_roles collection 
can you share with me . helpful for me

**Comment by AmitXShukla** [comment]
Thanks for reaching out. You will need to manually create it.
Please watch Part -1 video and take a screenshot from video and create it as is. (At least for admin collection)
Later, you can create a page in your app to setup, edit and update USER_ROLES collections.
I have this page in Pro level code but not in community version.

**Comment by JKAngular** [comment]
Hi

I follow your video but not coming correctly. can you help me

see this attachment

[image: image.png]

**Comment by AmitXShukla** [comment]
Image didn’t come up, 
also please make sure it’s
USER_ROLES, uppercase
it should match exactly as is, I’m in process of finishing next videos which should help you as well.

**Comment by JKAngular** [comment]
Hi
can you find attachment

**Comment by AmitXShukla** [comment]
No, I don’t see any attachment

**Comment by AmitXShukla** [comment]
I saw your image, sorry to say, yours doesn’t look like what I showed in video.
Please watch part of video again where I created a sample

USER_ROLES is a collection
admin is a document inside it
admin, addressbook etc each has a “map” inside 
Which has four fields each
visible Boolean true
read Boolean true
write Boolean true
delete Boolean true

**Comment by AmitXShukla** [comment]
Video #1
Fast forward at 13:18

**Comment by AmitXShukla** [comment]
![image](https://user-images.githubusercontent.com/20031132/79186856-a0efe500-7dcf-11ea-998c-890b58fd28e9.png)

**Comment by JKAngular** [comment]
hi

i tried so many time not working
see my snap shot. can you create snapshot step by step send me
thats helpful for me.

when i copy paste in your github there not shown user_roles why ?

[image: image.png]

**Comment by AmitXShukla** [comment]
Please try this one more time. I am in process of finishing detailed video and will upload those in a day or two.

USER_ROLES is a collection
admin is a document inside it
admin, addressbook etc are all individual fields and each is  of type “map”
Which has four fields each
visible Boolean true
read Boolean true
write Boolean true
delete Boolean true

**Comment by AmitXShukla** [comment]
I'm sure this screenshot will help you.

![image](https://user-images.githubusercontent.com/20031132/79258060-69208600-7e3f-11ea-844a-92925aa11f11.png)

**Comment by AmitXShukla** [comment]
![image](https://user-images.githubusercontent.com/20031132/79258144-8f462600-7e3f-11ea-8d32-ee39026c015f.png)

**Comment by JKAngular** [comment]
Hi
Mr. Amit Sir

Excellent !  Awesome .

thanks for your great help
now i created look like you

thanks thanks very much

But still now 3 menus only available here . how to set all menus coming
like your video

this is my output now

[image: image.png]

**Comment by JKAngular** [comment]
Thank you so much sir
but in our application menu coming 3 menu only how to change this

[image: image.png]

**Comment by JKAngular** [comment]
Dear Amit sir

but component not loading
i saw your github html is blank can you update or share the mail source
code sir.

this is your components

[image: image.png]

**Comment by JKAngular** [comment]
Amit sir

Menus not issue but your component html files blank can you update them or
can you share source code here.

**Comment by AmitXShukla** [comment]
Hi JK, please see, I am still in process of making videos and creating following modules, this is why files are blank.
It’s a huge project and I will adding one module code at a time.
Please wait for new videos.

So far, you already accomplished what I covered so far.

**Comment by JKAngular** [comment]
Hi
Amit

Thanks for your reply . Ok i am waiting for your instructions

Thanks for your Great help
