### ISSUE TITLE
How to create collection and map. your video shows already created one

### ISSUE THREAD

**Issue by JKAngular** [AmitXShukla/ERP-Apps-CRM-Cloud-Angular_Firebase#2]
Hi
Your code not created user_Roles . can you share step by step snapshot that only helpful for me.

see this image

![image](https://user-images.githubusercontent.com/59573064/79196124-14840780-7e4d-11ea-8615-5b8762c72e93.png)

**Comment by AmitXShukla** [comment]
Duplicate issue, - already fixed.

**Comment by JKAngular** [comment]
Hi
Amit

When i expect your fullsourcecode  push to Github
kindly inform me
