### ISSUE TITLE
when we first login with google showing this error

### ISSUE THREAD

**Issue by nilerajput91** [AmitXShukla/ERP-Apps-CRM-Cloud-Angular_Firebase#3]
![Screenshot (56)](https://user-images.githubusercontent.com/54884391/87660613-fb0c9780-c77c-11ea-8ebd-ad1a39f6096c.png)

**Comment by AmitXShukla** [comment]
> 
>This is very clear error, your Firebase rules are not setup correctly, Please make sure, you copy paste Firebase Rules exactly as-is from ReadMe.md file.

Also, please watch part # for quick installation and Part #4 for more details on how to setup Firebase rules.
These are long videos, but Please try not to skip content and fast forward.
https://www.youtube.com/playlist?list=PLp0TENYyY8lHNMTAlrfVQKzAvQo3yzHYk
