### ISSUE TITLE
getting error in setting up on localhost

### ISSUE THREAD

**Issue by ranjitaa** [AmitXShukla/ERP-Apps-CRM-Cloud-Angular_Firebase#4]
$ ng serve --open
An unhandled exception occurred: listen EADDRNOTAVAIL: address not available 192.168.64.2:4200
See "/private/var/folders/c6/s_mrmh_544j4wqtmz6l8lrym0000gn/T/ng-Seo1My/angular-errors.log" for further details.

Kindly tell, how to solve this..

**Comment by AmitXShukla** [comment]
looks like you are running some other apps on your machine, please restart your machine and run this app at first only, or try to free up any other ports. If still not resolved, look into Angular CLI documentation.
https://angular.io/cli/serve

**Comment by ranjitaa** [comment]
Thanks for replying... I have other projects of angular.. I am on Mac ... other projects are not running... I have setup database and everything for this project. but same problem is coming. I have latest version of NPM and angular.

**Comment by AmitXShukla** [comment]
You may have copy pasted entire repo and something went wrong in angular.json file.
Here are few things you can.
1. create a brand new project using Angular CLI and then do ng --serve,
make sure it run fine, then slowly start replacing source code, 
if this still doesn't work, there is something wrong the way NPM, angular is setup on your computer.
or if it doesn't work that means, something else on your mac is using port 4200 and you need to release this port
Google - how to check and release ports on local mac
2. take a deep look at angular.json file, there might be some setting preventing to run your app on port 4200
3. in your package.json file, try to use different port i..e other than 4200 like
"scripts": {
  "start": "ng serve --host foo.bar --port 80"
}
4. or just try ng serve --host=0.0.0.0:8080
