### ISSUE TITLE
Cannot read property 'uid' of null

### ISSUE THREAD

**Issue by thokozani1marc** [AmitXShukla/ERP-Apps-CRM-Cloud-Angular_Firebase#5]
Everything is correct I have followed the video and the GitHub code, but I am getting an error. I don't know where did I go wrote here. The error appears on **settings.component.ts** when I try to create a new admin.

**Comment by AmitXShukla** [comment]
can you please take a screenshot of error and upload it here

**Comment by AmitXShukla** [comment]
> 
> 
> Everything is correct I have followed the video and the GitHub code, but I am getting an error. I don't know where did I go wrote here. The error appears on **settings.component.ts** when I try to create a new admin.

Also, please see, YouTube videos do not reflect most current version.
if your coding is failing, this may be due to newer Angular release.
please always refer to This GitHub repository for most current source code.

https://github.com/AmitXShukla/ERP-Apps-CRM-Cloud-Angular_Firebase/blob/master/src/app/ui/auth/settings.component.ts

**Comment by thokozani1marc** [comment]
The screenshot of the error. I did watch the YouTube videos and I did use the newer Angular release. 

![error](https://user-images.githubusercontent.com/16365138/104282698-1f40fb00-54b8-11eb-92cf-aad317093422.PNG)

**Comment by AmitXShukla** [comment]
can you please make sure your settings file look like same as this link

https://github.com/AmitXShukla/ERP-Apps-CRM-Cloud-Angular_Firebase/blob/master/src/app/ui/auth/settings.component.ts

**Comment by AmitXShukla** [comment]
and please use all source code from this GitHub instead of YouTube videos.

**Comment by thokozani1marc** [comment]
Okay, I will double-check,

**Comment by thokozani1marc** [comment]
I managed to get it to work. Sorry, and I will delete this issue.
