### ISSUE TITLE
I am not able to make dropdown admin component visible

### ISSUE THREAD

**Issue by AyishaImran** [AmitXShukla/ERP-Apps-CRM-Cloud-Angular_Firebase#6]
I am trying to deveop an app and was following your youtube videos. i need to make 4 roles admin,senior manager,telecaller and counsellor. and was following your code and using firebase for backend. i exactly copied your code but i am not able to compile the code. backend.service.ts has get docs file and it shows the error that 'not all code paths return a value'. also in the header.component.html file dropdown item admin and address book shows the error(<input type="hidden" name="author" id="author" [ngModel]="(data$ | async)?.author" required>) that 'property admin does not exist on type unknown'. and in admin.component.html it shows the error again that ( <input matInput placeholder="Name" name="name" id="name" [ngModel]="(data$ | async)?.name" required) 'property admin does not exist on type unknown'. this error is shown for name ,phone,author,email,role etc. can you please help me with this. I am not using any of the crm properties. stuck with this for 2 days and nobody is there for me tio help. struggling with this and dont know what to do. I  can mail you or contact you if you are ready to hear about the problem in details. thanks in advance . Ayisha please help me I am in need .attaching the error photos with the mail. thank you
![IMG_20210802_164354](https://user-images.githubusercontent.com/88321991/127853827-58d24bc2-3235-4a09-a401-ddebc926d4ae.jpg)
![IMG_20210802_164403](https://user-images.githubusercontent.com/88321991/127853836-5d9401fd-5a4c-4c65-be7f-c7a445767f5a.jpg)
![IMG_20210802_164413](https://user-images.githubusercontent.com/88321991/127853841-a5d7ab4b-8a15-43f8-8768-6eec577f8ce7.jpg)
![IMG_20210802_164423](https://user-images.githubusercontent.com/88321991/127853843-959054fc-3931-49dc-ad82-c31cb5903f3f.jpg)

**Comment by AmitXShukla** [comment]
Thanks, let me download this repository, and see what's wrong with this code. Please expect an answer  tomorrow. I assume, this is the code you copied as is and has not make any changes yet, what is angular version ? (I will assume you are using latest) - Amit

**Comment by AmitXShukla** [comment]
I'm sure, this has something to do with Angular version, now Angular 12 is released,
please make sure, you package.json file exactly matches with package.json file show in this repository, and do a ng vrersion and let me know what Angular Global version you have installed.
node -v, npm -v (also node and npm version, Angular 11 and Angular 12 need latest node and npm as well).

![image](https://user-images.githubusercontent.com/20031132/127919695-42b44590-06fa-4c10-b4b8-55ae936067e8.png)

**Comment by AyishaImran** [comment]
Thank you very much for your reply I am using angular 12 for the project. Now firebase has two database systems firestore database and realtime time database I am using firestore database. I have copied the code as such. I have to make some changes to the roles since I need 3-4 roles. But I thought that I will do it after making this work . Should I push the code here. I am helpless right now. I am so glad that you replied 
![IMG_20210803_074510](https://user-images.githubusercontent.com/88321991/127946985-9526b1c9-a494-4e72-9040-9b94ef02726e.jpg)
![IMG_20210803_074504](https://user-images.githubusercontent.com/88321991/127946989-df800a3c-5514-40f7-94a3-daff960d3485.jpg)

**Comment by AyishaImran** [comment]
I am ready to push the code here if that's possible

**Comment by AmitXShukla** [comment]
go to your terminal window , browse to the directory where you downloaded this project and run these commands and send me results please
node -v
npm -v
ng version
ng serve

I assume, you have copied this project as is and trying to run it first time.
let's make sure this code runs without any error first time and later you can make changes and add roles.

**Comment by AyishaImran** [comment]
Yes...I have not downloaded the project. I have watched your videos one by one did code on my own. After that when error arised I went to the repository and copied all the files that I need because I don't need any components related to crm. I needed only some functions of the app so copied the needed components and changes routing and app module according to that. I mainly need admin page and address book page. I will attach the photos. 
![IMG_20210803_074504](https://user-images.githubusercontent.com/88321991/127953721-13302695-d475-469b-a892-0aa0711afc24.jpg)
![IMG_20210803_074510](https://user-images.githubusercontent.com/88321991/127953771-a000cf05-562d-4f88-922e-6afcc99ae8f4.jpg)
![IMG_20210803_090220](https://user-images.githubusercontent.com/88321991/127953777-0ab0c4af-977a-444a-8b54-ffa39e7d6815.jpg)

**Comment by AyishaImran** [comment]
I have already installed a new version of node and angular to the project. So if I pull the code from here directly it will create conflicts right .?

**Comment by AyishaImran** [comment]
Should I copy the whole project. what about the node version and angular version then. I have installed node 14 in my system and angular 12 is used in my app. So will I be able to pull your code and run it in my system

**Comment by AmitXShukla** [comment]
> 
> 
> Should I copy the whole project. what about the node version and angular version then. I have installed node 14 in my system and angular 12 is used in my app. So will I be able to pull your code and run it in my system

if you have not made any changes to this project, then ignore it, I can download this from GitHub same copy. please try running one more command

npm install --save

**Comment by AyishaImran** [comment]
Actually i followed youyr videos and wrote the code along with that. but when error arised tried to copy the code from github and copied the required components and tried to run. that's when i got these errors.

**Comment by AyishaImran** [comment]
now uninstalled node and trying to download the node 14 version

**Comment by AmitXShukla** [comment]
please join me at google chat  amit@elishconsulting.com

**Comment by AmitXShukla** [comment]
Issue is resolved now.
